### ISSUE TITLE
Error `Cannot destructure property 't' of 'i18n' as it is undefined.`

### ISSUE THREAD

**Issue by zoey-kaiser** [xibman/nuxt-zod-i18n#17]
### Environment

------------------------------
- Operating System: Darwin
- Node Version:     v20.6.1
- Nuxt Version:     3.9.1
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.7.5
- Builder:          -
- User Config:      experimental, css, modules, build, devtools, sourcemap, typescript, auth, formkit, i18n
- Runtime Modules:  @sidebase/nuxt-auth@0.6.4, @nuxtjs/tailwindcss@6.10.4, @bg-dev/nuxt-naiveui@1.8.1, @formkit/nuxt@1.4.0, @nuxtjs/i18n@8.0.0, nuxt-zod-i18n@1.3.0, nuxt-icon@0.6.8, @vueuse/nuxt@10.7.2
- Build Modules:    -
------------------------------

### Version

v1.3.0

### Reproduction

https://stackblitz.com/edit/nuxt-starter-dpc9kz?file=nuxt.config.ts

### Description

I installed `nuxt-zod-i18n` after I had already been using `@nuxtjs/i18n` for a while. I added it to the `modules` in the `nuxt.config.ts` and got the error that `'t' of 'i18n' is undefined.` and therefore cannot be accessed. 

The same error happened in a minimal stackblitz reproduction (also linked above).

### Logs

```shell-script
[nuxt] [request error] [unhandled] [500] Cannot destructure property 't' of 'i18n' as it is undefined.
  at ./node_modules/.pnpm/nuxt-zod-i18n@1.3.0_rollup@4.9.4/node_modules/nuxt-zod-i18n/dist/runtime/plugin.mjs:10:11
  at ./virtual:nuxt:/Users/zoeykaiser/Documents/Development/Sidestream/dikoma/.nuxt/plugins/server.mjs:52:89
  at Module.executeAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:111:19)
  at setup (./virtual:nuxt:/Users/zoeykaiser/Documents/Development/Sidestream/dikoma/.nuxt/plugins/server.mjs:52:65)
  at ./node_modules/.pnpm/nuxt@3.9.1_@types+node@20.10.8_eslint@8.56.0_rollup@4.9.4_typescript@5.3.3_vite@5.0.11_vue-tsc@1.8.27/node_modules/nuxt/dist/app/nuxt.js:116:60
  at fn (./node_modules/.pnpm/nuxt@3.9.1_@types+node@20.10.8_eslint@8.56.0_rollup@4.9.4_typescript@5.3.3_vite@5.0.11_vue-tsc@1.8.27/node_modules/nuxt/dist/app/nuxt.js:191:44)
  at Object.callAsync (./node_modules/.pnpm/unctx@2.3.1/node_modules/unctx/dist/index.mjs:68:55)
  at ./node_modules/.pnpm/nuxt@3.9.1_@types+node@20.10.8_eslint@8.56.0_rollup@4.9.4_typescript@5.3.3_vite@5.0.11_vue-tsc@1.8.27/node_modules/nuxt/dist/app/nuxt.js:193:56
  at Object.runWithContext (./node_modules/.pnpm/@vue+runtime-core@3.4.7/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3998:18)
  at callWithNuxt (./node_modules/.pnpm/nuxt@3.9.1_@types+node@20.10.8_eslint@8.56.0_rollup@4.9.4_typescript@5.3.3_vite@5.0.11_vue-tsc@1.8.27/node_modules/nuxt/dist/app/nuxt.js:193:24)
```

**Comment by zoey-kaiser** [comment]
I had a look into your code and I assume it may be because of how you import `$i18n` in https://github.com/xibman/nuxt-zod-i18n/blob/main/src/runtime/plugin.ts#L9.


Maybe accessing it via `const { $i18n } = useNuxtApp` imported from `import { useNuxtApp } from "#imports"` could resolve the issue?

**Comment by xibman** [comment]
@zoey-kaiser i take a look tonight. 

As the same time i will update the dependencies. 

Thanks for you're report !

**Comment by zoey-kaiser** [comment]
Sounds good! Thank you very much 🥰

**Comment by xibman** [comment]
@zoey-kaiser  it's not a bug.

You need to load this plugin before nuxt-i18n

`modules: ['@nuxtjs/i18n', 'nuxt-zod-i18n']`   ----->      `modules: ['nuxt-zod-i18n', '@nuxtjs/i18n']`

I already put a warning into the doc. I try to add an other one

**Comment by xibman** [comment]
The project inject zod translations keys into a reserved namespace.

So your key  'test.name is' not crushed.

**Comment by xibman** [comment]
@zoey-kaiser I just try this morning with your playground.

As i suspect the problem comes from the translation loaded. You only put  'de-DE' translation but the plugin also push other language. For me the system try to push english translation due to my browser language. But in english the key `test.name` does not exist.
If i switch my language to 'de-DE' no problem the translation is available.

See this error on the console 

```
[intlify] Not found 'test.name' key in 'en-GB' locale messages

[intlify] Fall back to translate 'test.name' key with 'en' locale

Not found 'test.name' key in 'en' locale messages.
```

**Comment by xibman** [comment]
I think i can track user config and try to filter language loaded by the plugin by default.
Plus add possibility to restrict language that are loaded by the plugin with an array of language.

**Comment by zoey-kaiser** [comment]
> I think i can track user config and try to filter language loaded by the plugin by default.

I think this would be a great feature to use! You could check via the nuxt i18n config, which locales are enabled and which one is the default and mirror those settings to your module!

**Comment by xibman** [comment]
@zoey-kaiser  Hi,

I add the optimization to the module.
But you also need to configure nuxt/i18n to fallback to a locale if nothing found.

check https://stackblitz.com/edit/nuxt-starter-coj6l2?file=nuxt.config.ts

**Comment by xibman** [comment]
@zoey-kaiser Can you confirm your problem i solved ?

**Comment by zoey-kaiser** [comment]
I can confirm it works now 🥳

Thank you so much for your help and improvements! For anyone referring back to this issue, you can find the Stackblitz with the updated version and a functional demo here: https://stackblitz.com/edit/nuxt-starter-dpc9kz?file=locales%2Fde-DE.json
