### ISSUE TITLE
Unable to load `i18n.config.ts` config file

### ISSUE THREAD

**Issue by XavierChevalier** [xibman/nuxt-zod-i18n#18]
### Environment

- Operating System: Darwin
- Node Version:     v20.2.0
- Nuxt Version:     3.9.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.15.0
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -

### Version

v1.4.0

### Reproduction

-

### Description

Actually, is not possible to use `nuxt-zod-i18n` with external `@nuxtjs/i18n` configuration file like [`i18n.config.ts`](https://i18n.nuxtjs.org/getting-started/basic-usage#translate-with-vue-i18n).

`nuxt-zod-i18n` only load i18n configuration from the `nuxt.config.ts` file. See this line:
https://github.com/xibman/nuxt-zod-i18n/blob/0f85d9ac5193b40533ad5d96fcc9e4df783c2a38/src/module.ts#L42

We need to be able to load the configuration of this external file, based on the path defined in the [Nuxt configuration or `'./i18n.config.ts'` by default](https://i18n.nuxtjs.org/getting-started/basic-usage#translate-with-vue-i18n).

```ts
export default defineNuxtConfig({
  // ...
  i18n: {
    vueI18n: './my-i18n.config.ts' // optional, './i18n.config.ts' by default 
  }
})
```

**Comment by xibman** [comment]
@XavierChevalier I try to had this possibility next week

**Comment by xibman** [comment]
@XavierChevalier  Can you explain more why you need this.

Because the configuration contain by  `vueI18n: './my-i18n.config.ts' ` is for vue-i18n at runtime.

I'm not really sure this is required

**Comment by xibman** [comment]
@XavierChevalier  any news ?
