### ISSUE TITLE
Docs homepage is dead

### ISSUE THREAD

**Issue by antfu** [xibman/nuxt-zod-i18n#32]
### Description

[xibman-nuxt-zod-i18n.nuxt.space/](http://xibman-nuxt-zod-i18n.nuxt.space/) not displaying the content, and returns 404 in status code

**Comment by xibman** [comment]
Thanks for the notice @antfu  on it this afternoon !

**Comment by xibman** [comment]
Back on track !

**Comment by xibman** [comment]
Fixed by https://github.com/nuxt-ui-pro/docs/pull/71
