### ISSUE TITLE
[intlify] Not found 'zodI18n.errors.invalid_type_received_undefined' key in 'en' locale messages.

### ISSUE THREAD

**Issue by team-obi-wan** [xibman/nuxt-zod-i18n#41]
### Environment

- Operating System: `Darwin`
- Node Version:     `v20.2.0`
- Nuxt Version:     `3.14.1592`
- CLI Version:      `3.15.0`
- Nitro Version:    `2.10.4`
- Package Manager:  `npm@9.6.6`
- Builder:          `-`
- User Config:      `default`
- Runtime Modules:  `@nuxt/ui@3.0.0-alpha.10`, `@sidebase/nuxt-auth@0.9.4`, `@nuxt/test-utils/module@3.14.4`, `nuxt-zod-i18n@1.11.2`, `@nuxtjs/i18n@9.1.1`
- Build Modules:    `-`

### Version

1.11.2

### Reproduction

i installed it using quick setup

### Description

i installed it using Quick Setup and i have a simple schema 
`export const loginSchema = z.object({
    email: z.string().email(),
    password: z.string(),
});`

However, when I load the page and enter an invalid email, the message displayed is “zodI18n.errors.invalid_string.email”. In the console log, I see: “intlify Not found ‘zodI18n.errors.invalid_type_received_undefined’ key in ‘en’ locale messages.”

### Logs

```shell-script
intlify Not found ‘zodI18n.errors.invalid_type_received_undefined’ key in ‘en’ locale messages.
```

**Comment by xibman** [comment]
Hi,

I think the problem comes from the language binding.

Can you share your i18n language config please ?

**Comment by hasan-ozbey** [comment]
I have the same issue, here's my config

```
i18n: {
    defaultDirection: 'ltr',
    defaultLocale: 'en-US',
    restructureDir: './app/i18n',
    langDir: './locales',
    lazy: true,
    strategy: 'prefix_except_default',
    types: 'composition',
    locales: [
      {
        code: 'en-US',
        name: 'English',
        dir: 'ltr',
        file: 'en-US.json',
        isCatchallLocale: true,
        language: 'en-US',
      },
      {
        code: 'tr-TR',
        name: 'Türkçe',
        dir: 'ltr',
        file: 'tr-TR.json',
        language: 'tr-TR',
      },
    ],
  },

  zodI18n: {
    localeCodesMapping: {
      'en-GB': 'en-US',
    },
  },
  ```
  
  my locale files are in
  
  [root]/app/i18n/locales/tr-TR.json
  [root]/app/i18n/locales/en-US.json

**Comment by harkor** [comment]
I have exactly same issue on my side.

```json
{
  "nuxt": "^3.15.4",
  "@nuxtjs/i18n": "9.2.1",
  "nuxt-zod-i18n": "1.11.5",
  "zod": "^3.24.2"
}
```

```ts
  modules: [
    "@nuxtjs/i18n",
    "nuxt-zod-i18n",
  ],
  i18n: {
    locales: [
      {
        code: "fr",
        name: "Français",
        language: "fr-FR",
      },
    ],
    defaultLocale: "fr",
  },
  zodI18n: {
    localeCodesMapping: {
      "fr-FR": "fr",
    },
  }
```

**Comment by xibman** [comment]
@harkor just swap modules order in your config 

form 
```ts
modules: [
    "@nuxtjs/i18n",
    "nuxt-zod-i18n",
  ],
```

TO: 
modules: [
    "@nuxtjs/i18n",
    
  ],

**Comment by harkor** [comment]
Oh, sorry for that... Maybe make this part more visible about the order ?

Thanks

**Comment by alex-eri** [comment]
In my case `en` works, but other - not.

```
  zodI18n: {
    localeCodesMapping: {
      'en-US': 'en',
      'en-GB': 'en',
      'ru-RU': 'ru'
    }
  },
  i18n: {
    locales: [
      { code: 'en', language: 'en-US' },
      { code: 'ru', language: 'ru-RU' }
    ],
    defaultLocale: 'en',
    detectBrowserLanguage: {
      useCookie: true,
      alwaysRedirect: true,
      cookieCrossOrigin: true
    }
  },


  modules: [
    'nuxt-zod-i18n',
    '@nuxtjs/i18n',
    '@nuxt/icon',
    '@nuxt/image',
    '@nuxt/fonts',
    '@nuxt/eslint',
    '@nuxt/content',
    '@nuxt/ui-pro',
    'nuxt-auth-utils',
  ]


```

**Comment by xibman** [comment]
@alex-eri try to check during the week

**Comment by alex-eri** [comment]
Only default localization works. I make one locale default and error happen on another. 

Maybe SSR related.

**Comment by alex-eri** [comment]
Only default localization works. I make one locale default and error happen on another. 

Maybe SSR related. 

I will provide minimal reproducing example tomorow.

**Comment by alex-eri** [comment]
https://github.com/alex-eri/zodi18nbug-41

steps to reproduce:

- reload page

- change language

- type invalid email

- change field to see error in default language (sometime error code)

**Comment by xibman** [comment]
Hi Alex can you set you debug repository to public i can not acces it at the moment

**Comment by alex-eri** [comment]
> public

sorry, @xibman (missclicked).  done
